# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 20:53
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField(default=datetime.datetime(2017, 9, 5, 20, 53, 19, 864000))),
                ('fecha_hora_salida', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('aforo_maximo', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emplazamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('poblacion', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('cp', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('pais', models.CharField(max_length=30)),
                ('coordenadas', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grabador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('puerto', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lectore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('id_dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Dependencia')),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('1', 'OK'), ('2', 'ERR. LECTOR NO EXISTE'), ('3', 'ERR. USUARIO NO EXISTE'), ('4', 'ERR. USUARIO NO TIENE PERMISOS'), ('5', 'ERR. EVENTO NO EXISTE'), ('6', 'ERR. EVENTO NO ACTIVO'), ('7', 'ERR. AFORO LLENO')], max_length=1)),
                ('contenido', models.CharField(max_length=300)),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Lectore')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=9, null=True, unique=True)),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('poblacion', models.CharField(max_length=30, null=True)),
                ('provincia', models.CharField(max_length=30, null=True)),
                ('cp', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999)])),
                ('pais', models.CharField(max_length=30, null=True)),
                ('grabador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Grabador')),
                ('permisos', models.ManyToManyField(to='webService.Dependencia')),
            ],
        ),
        migrations.AddField(
            model_name='dependencia',
            name='id_emplazamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Emplazamiento'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='id_lector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Lectore'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='id_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Dependencia'),
        ),
        migrations.AddField(
            model_name='acceso',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Usuario'),
        ),
    ]
