# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:16
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesos',
            name='fecha_hora_entrada',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 17, 16, 9, 54000)),
        ),
        migrations.RemoveField(
            model_name='organizacione',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='organizacione',
            name='id_usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
