# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 21:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='fecha_hora_entrada',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 21, 21, 51, 126000)),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='estado',
            field=models.CharField(choices=[('1', 'OK'), ('2', 'ERR. LECTOR NO EXISTE'), ('3', 'ERR. USUARIO NO EXISTE'), ('4', 'ERR. USUARIO NO TIENE PERMISOS'), ('5', 'ERR. AFORO LLENO')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='id_lector',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
