# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-05 21:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0002_auto_20170905_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='aforo_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='fecha_hora_entrada',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 5, 21, 27, 19, 410000)),
        ),
    ]
