# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0002_auto_20170804_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacione',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='emplazamiento',
            name='id_organizacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_organizacion',
        ),
        migrations.AlterField(
            model_name='accesos',
            name='fecha_hora_entrada',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 17, 22, 26, 631000)),
        ),
        migrations.DeleteModel(
            name='Organizacione',
        ),
    ]
