# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 19:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0003_auto_20170905_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceso',
            old_name='id_sala',
            new_name='id_dependencia',
        ),
        migrations.AlterField(
            model_name='acceso',
            name='fecha_hora_entrada',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 6, 19, 9, 39, 869000)),
        ),
    ]
