# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0003_auto_20170804_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_entrada', models.DateTimeField(default=datetime.datetime(2017, 8, 6, 17, 1, 38, 115000))),
                ('fecha_hora_salida', models.DateTimeField(default=None, null=True)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Evento')),
                ('id_lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Lectore')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webService.Usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='accesos',
            name='id_eventos',
        ),
        migrations.RemoveField(
            model_name='accesos',
            name='id_lector',
        ),
        migrations.RemoveField(
            model_name='accesos',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Accesos',
        ),
    ]
