# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webService', '0004_auto_20170906_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceso',
            name='fecha_hora_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='acceso',
            name='fecha_hora_salida',
            field=models.DateTimeField(null=True),
        ),
    ]
